jobs:
  build:
    name: Java ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: ./.github/scripts/build.sh
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        os:
        - ubuntu-latest
name: Build and Test
on:
  repository_dispatch:
    types: trigger-ga___build.yml
