jobs:
  publish:
    environment: jfrog-publish
    name: Java ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      env:
        JFROG_KEY: ${{ secrets.JFROG_KEY }}
        JFROG_USER: ${{ secrets.JFROG_USER }}
      run: ./.github/scripts/publish.sh
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
name: Build and Publish
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
